server:
  port: 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:4004"
                  - "http://localhost:8080"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS

          routes:
            - id: patient-service
              uri: http://patient-service:8080
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1

            - id: api-docs-patient-route
              uri: http://patient-service:8080
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs

            - id: swagger-ui-route
              uri: http://patient-service:8080
              predicates:
                - Path=/swagger-ui/**,/swagger-ui.html,/v3/api-docs/**
              filters:
                - PreserveHostHeader